language: rust
sudo: true
cache: cargo
os:
  - linux

matrix:
  fast_finish: false
  include:
  - rust: stable
    script:
      # Run tests/builds
      - cargo check
      - cargo build --release --verbose --all
      - cargo test --release --verbose --all
      
  
  - rust: nightly
    script:
      # Run tests/builds
      - cargo check
      - cargo build --release --verbose --all
      - cargo test --release --verbose --all


# Send a notification to the Dusk build Status Telegram channel once the CI build completes
after_script:
  - bash <(curl -s https://raw.githubusercontent.com/dusk-network/tools/master/bash/telegram_ci_notifications.sh)