[package]
name = "poseidon252"
version = "0.5.0"
authors = [
  "zer0 <matteo@dusk.network>",	"vlopes11 <victor@dusk.network>",	"CPerezz <carlos@dusk.network>", "Kristoffer Ström <kristoffer@dusk.network>"
]
edition = "2018"

[dependencies]
kelvin = "0.18"
nstack = "0.4"
lazy_static = "1.3.0"
hades252 = { git = "https://github.com/dusk-network/hades252", version = "0.6.0" }
# Depends on unpublished changes - set version after jubjub bump
dusk-jubjub = { git = "https://github.com/dusk-network/jubjub", branch = "vlopes11/10-dhke" }
dusk-plonk = { version = "0.2.0", features = ["trace-print"] }
rand = "0.7"

[dev-dependencies]
rand_core = "0.5"
criterion = "0.3"

[profile.dev]
opt-level = 3
debug = false
rpath = false
lto = false
debug-assertions = false
codegen-units = 16
panic = 'unwind'
incremental = false
overflow-checks = false


[profile.release]
debug = false
panic = 'abort'
lto = true
incremental = false
codegen-units = 1
